version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: :${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
